### ISSUE TITLE
An issue on G

### ISSUE THREAD

**Issue by guangingmai** [jdmagasin/nifH-ASV-workflow#13]
Hi Magasin, I installed nifh-ASV-workflow with mamba, ran the test data in the provided file, and the log file returned an issue.
<img width="605" alt="Snipaste_2024-11-26_11-01-57" src="https://github.com/user-attachments/assets/596160af-e604-42c6-b9e3-ddcff0c76b39">
Does i install the software incompletely?
[log.log](https://github.com/user-attachments/files/17912123/log.log)

**Comment by jdmagasin** [comment]
Hello.  Yes, the software appears to be installed and running correctly.  The GatherAsvs stage completed, and the numbers of AUIDs, samples and reads equal the numbers I got  on November 22. (I reran the workflow to test a change to the .yml files to specify exact package versions, rather than minimum versions.)

The "exit 0" failure message is an error.  It has no consequences on the outputs.  However, it is confusing and I will fix the error.

The "clock skew detected" warning from make suggests that an output file is newer than one of the files it depends on.  [Here](https://www.baeldung.com/linux/make-clock-skew-warning) is a brief explanation.  I do not see this warning when I run GatherAsvs for the first time.  (Or you can first do "make clean" and it probably will not happen.)

However, to debug the clock skew:  Perhaps run GatherAsvs with "make -d" will provide more information on which output file causes the warning.  And you can check the timestamps of your files/directories.

**Comment by jdmagasin** [comment]
Fixed the confusing "exit 0" error with commit 2bc9fc64d75f84e34b2f02e775d786c52c464db6.  
The clock skew warning does not happen when doing a clean make.  Will follow up on the skew once output from "make -d" is received.

**Comment by guangingmai** [comment]
Hi Magasin, thank you for your prompt reply . The "exit 0" failure message was fixed by following the modification of the _identifyChimeras.sh_.
But the clock skew cannnot be fixed by "make clean", and i ran GatherAsvs with "make -d", with the following log file.
[log.txt](https://github.com/user-attachments/files/17927926/log.txt)
Does the clock skew warning have something on the results? If not, i would probably ignore it.

**Comment by jdmagasin** [comment]
Hello @guangingmai .  Thanks for trying "make -d".  In the  log.txt "skew" does not appear.  So I think that you did:
```
make clean
make -d
```

I think the the clock skew warning can probably be ignored because the AUID, samples, and read totals you reported are the same that I got with a clean build (i.e. every output file was newly created). 

I will close the issue.  However, if you do run into the clock skew warning again let me know.  Thanks!
