### ISSUE TITLE
AnnotateAuids script make_primary_taxon_id.py requires at least one AUID to be UCYN-A

### ISSUE THREAD

**Issue by guangingmai** [jdmagasin/nifH-ASV-workflow#14]
Hi Magasin. I encountered a error in annotation stage, the log file was as followed.
[log.log](https://github.com/user-attachments/files/17935159/log.log)
I provided the textdata file what i ran.
[TextData.zip](https://github.com/user-attachments/files/17935260/TextData.zip)

**Comment by jdmagasin** [comment]
Hi @guangingmai.  The key part of the log is here:
```
>>>>> Creating final annotation table auids.annot.tsv which includes primary taxon ID <<<<<
make_primary_taxon_id.py is currently running...
Attempting to read input annotation table 'auids.annot.raw.tsv'
Cleaning columns...
Error: The following required columns contain only NA values: UCYNAoligos.description

Script 'make_primary_taxon_id.py' exited with an error.
No primary ID was made and no output was written! :(

make: *** [Makefile:273: auids.annot.tsv] Error 1
```

The script make_primary_taxon_id.py requires that all columns have at least one annotation (line 206).  This requirement should be removed, but it will take some time to make and verify the fix.  Two possible ways to work around the bug are below.

Question: I thought that you were running the workflow on all the studies under nifH-ASV-workflow/Data (based on your GatherAsvs log provided in issue #13 .  If so, then this bug should not occur because there are AUIDs that have hits to the UCYN-A oligos database.  Are you now running the workflow only on your own datasets?  (The bug can only occur if no samples have UCYN-A.)

To avoid the bug, you can include a dataset that has UCYN-A.  AUID.106 is UCYN-A1 and it occurs in many studies.  I suggest picking a small study so the workflow runs more quickly.  AUID.106 occurs in 5 of the 6 samples in Tang_2020.  So if you run the workflow with your data and also Tang_2020, the bug will not occur. 

Alternatively, you can modify the FilterAuids output auids.annot.raw.tsv so that one AUID has non-NA values in the columns that start with "UCYNAoligos." .  The AUID will get an incorrect primary_id in the final output file auids.annot.tsv, which you can manually correct.

**Comment by guangingmai** [comment]
Hi @jdmagasin. I added one AUID of UCYN-A in the FilterAuids output auid.filtered.fasta, and everything went fine. Thanks.

**Comment by guangingmai** [comment]
Hi @jdmagasin, there is another nifh dada2 database in https://github.com/moyn413/nifHdada2. What differneces between this and the databases provided?

**Comment by jdmagasin** [comment]
Hi @guangingmai. Glad to hear it:)  If you created a new AUID, be sure to remove it from auids.annot.tsv.  If you leave the new AUID, then later in WorkspaceStartup you will get an error because of the extra AUID.  [Here](https://github.com/jdmagasin/nifH-ASV-workflow/blob/2bc9fc64d75f84e34b2f02e775d786c52c464db6/WorkspaceStartup/scripts/make_nifH_ASV_database.R#L232C1-L234C50) you can see the code that checks that AUIDs are the same in all tables for the nifH ASV database.

**Comment by jdmagasin** [comment]
> Hi @jdmagasin, there is another nifh dada2 database in https://github.com/moyn413/nifHdada2. What differneces between this and the databases provided?

That is not an ASV database created from _nifH_ amplicon datasets.  That database is created from reference _nifH_ sequences (many obtained from GenBank using ARBitrator).

**Comment by guangingmai** [comment]
OK, thank you for you reply. I would combine the results of databases your provided and nifHdada2.

**Comment by mo-morando** [comment]
Initially, our annotation table and primary ID script were designed with massive datasets in mind, necessitating certain columns as mandatory. However, we've recognized that this approach doesn't suit all scenarios, particularly:
- Smaller datasets
- Samples from less diverse regions
- Collections lacking UCYN-A or prominent NDC/cyano Marine Diazos database entries

To address these limitations, we've simplified the script to require only the essential columns:
- subcluster
- cluster
- Genome879.pctId
- Genome879.tax
These columns are fundamental for generating a primary ID, and any valid dataset should have at least one hit for each. If these designations cannot be obtained, it may indicate a more significant issue with the data.

**These changes have been implemented**

**Next Steps**
@guangingmai, please rerun your data and inform us of any issues you encounter. Your feedback will be valuable in ensuring the effectiveness of these modifications.

Thank you for your patience and collaboration in improving our process.

**Comment by guangingmai** [comment]
Thank you for your improvements. Whether the [nifHdada2]( https://github.com/moyn413/nifHdada2) database can be added to the nifh-ASV-workflow?

**Comment by mo-morando** [comment]
You are very welcome.

Can you please be more specific? What are you asking to be done? Sorry I
don’t quite understand what you mean.

**Comment by guangingmai** [comment]
Considering the most diversity of nifH gene in ocean, it is highly recommended that you can contain  [nifHdada2](https://github.com/moyn413/nifHdada2) database provided by moyn413 in the AnnotateAuids step in the nifh-ASV-workflow.
> > Hi @jdmagasin, there is another nifh dada2 database in https://github.com/moyn413/nifHdada2. What differneces between this and the databases provided?
> 
> That is not an ASV database created from _nifH_ amplicon datasets. That database is created from reference _nifH_ sequences (many obtained from GenBank using ARBitrator).

**Comment by jdmagasin** [comment]
Thanks @mo-morando for the fix.  Will close the issue.

@guangingmai , 92% of the sequences in the most recent version of the [moyn413 nifHdada2 database (v2.0.5)](https://github.com/moyn413/nifHdada2) are already searched by our workflow's AnnotateAuids stage:  This includes 19K in ARB 2017, and a few more NCD's and cyanos from Kendra Turk-Kubo, which altogether comprise most of the 20K sequences in moyn413's nifHdada2.

We should update our ARB database and then use the updated ARB DB in our workflow.  This will capture most (>1200) of the new sequences in nifHdada2 v2.0.5. At that time we can check if any sequences are missed and decide how best to include them.  (A full search of nifHdada2 would slow down the workflow and would be redundant with ARB.)

For now, if you want to search moyn413 nifHdada2, you could make a local blast DB using [the v2.0.5 fasta](https://github.com/moyn413/nifHdada2/blob/master/nifH_dada2_v2.0.5.fasta).  (NCBI blast tools are included in your nifH_ASV_workflow environment.)  The definition lines in that FASTA have taxonomic information only.  If you like, you could change them to have identifiers in the [v2.0.5 csv](https://github.com/moyn413/nifHdada2/blob/master/nifH_dada2_phylum_v2.0.5.csv).
